#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET
app_front_login:
    path: /user/login
    controller: App\Controller\Front\UserController::login